export const GET_ORDER_REQUEST = "GET_ORDER_REQUEST"
export const GET_ORDER_SUCCESS = "GET_ORDER_SUCCESS"
export const GET_ORDER_FAILER = "GET_ORDER_FAILER"

export const CONFIRM_ORDER_REQUEST = "CONFIRM_ORDER_REQUEST"
export const CONFIRM_ORDER_SUCCESS = "CONFIRM_ORDER_SUCCESS"
export const CONFIRM_ORDER_FAILER = "CONFIRM_ORDER_FAILER"

export const PLACED_ORDER_REQUEST = "PLACED_ORDER_REQUEST"
export const PLACED_ORDER_SUCCESS = "PLACED_ORDER_SUCCESS"
export const PLACED_ORDER_FAILER = "PLACED_ORDER_FAILER"

export const DELIVERED_ORDER_REQUEST = "DELIVERED_ORDER_REQUEST"
export const DELIVERED_ORDER_SUCCESS = "DELIVERED_ORDER_SUCCESS"
export const DELIVERED_ORDER_FAILER = "DELIVERED_ORDER_FAILER"

export const CANCELED_ORDER_REQUEST = "CANCELED_ORDER_REQUEST"
export const CANCELED_ORDER_SUCCESS = "CANCELED_ORDER_SUCCESS"
export const CANCELED_ORDER_FAILER = "CANCELED_ORDER_FAILER"

export const DELETE_ORDER_REQUEST = "DELETE_ORDER_REQUEST"
export const DELETE_ORDER_SUCCESS = "DELETE_ORDER_SUCCESS"
export const DELETE_ORDER_FAILER = "DELETE_ORDER_FAILER"

export const SHIP_ORDER_REQUEST = "SHIP_ORDER_REQUEST"
export const SHIP_ORDER_SUCCESS = "SHIP_ORDER_SUCCESS"
export const SHIP_ORDER_FAILER = "SHIP_ORDER_FAILER"