export const CREATE_ORDER_REQUEST = "CREATE_ORDER_REQUEST"
export const CREATE_ORDER_SUCCESS = "CREATE_ORDER_SUCCESS"
export const CREATE_ORDER_FAILER = "CREATE_ORDER_FAILER"

export const GET_ORDER_BY_ID_REQUEST = "GET_ORDER_BY_ID_REQUEST"
export const GET_ORDER_BY_ID_SUCCESS = "GET_ORDER_BY_ID_SUCCESS"
export const GET_ORDER_BY_ID_FAILER = "_CARTFAILER"

// export const GET_ORDER_HISTORY_SUCCESS = "GET_ORDER_HISTORY_SUCCESS"
// export const GET_ORDER_HISTORY_REQUEST = "GET_ORDER_HISTORY_REQUEST"
// export const GET_ORDER_HISTORY_FAILER = "GET_ORDER_HISTORY_FAILER"
