export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCR_BU_ID_REQUEST"
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCR_BU_ID_REQUEST_SUCCESS"
export const FIND_PRODUCT_BY_ID_FAILER = "FIND_PRODUCR_BU_ID_REQUEST_FAILER"

export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCRS_REQUEST"
export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCRS_REQUEST_SUCCESS"
export const FIND_PRODUCTS_FAILER = "FIND_PRODUCRS_REQUEST_FAILER"

export const DELETE_PRODUCT_REQUEST = "DELETE_PRODUCT_REQUEST"
export const DELETE_PRODUCT_SUCCESS = "DELETE_PRODUCT_SUCCESS"
export const DELETE_PRODUCT_FAILER = "DELETE_PRODUCT_FAILER"

export const CREATE_PRODUCT_REQUEST = "CREATE_PRODUCT_REQUEST"
export const CREATE_PRODUCT_SUCCESS = "CREATE_PRODUCT_SUCCESS"
export const CREATE_PRODUCT_FAILER = "CREATE_PRODUCT_FAILER"