export const FIND_PRODUCT_BY_ID_REQUEST = "FIND_PRODUCR_BU_ID_REQUEST"
export const FIND_PRODUCT_BY_ID_SUCCESS = "FIND_PRODUCR_BU_ID_REQUEST_SUCCESS"
export const FIND_PRODUCT_BY_ID_FAILER = "FIND_PRODUCR_BU_ID_REQUEST_FAILER"

export const FIND_PRODUCTS_REQUEST = "FIND_PRODUCRS_REQUEST"
export const FIND_PRODUCTS_SUCCESS = "FIND_PRODUCRS_REQUEST_SUCCESS"
export const FIND_PRODUCTS_FAILER = "FIND_PRODUCRS_REQUEST_FAILER"